spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 133263333905-llvbqpcugfecbrggh9eikjd8tlpbtlk5.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "{baseUrl}/auth/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile

jwt:
  # base64 encoded key
  secret: 9i3Bk8SJ3CfqIm+v9JJjHc5PGmqNmevaXDLYX4k0sW9hmhuvA6rTNWIM6uISlbVWcn28bMs+gY+P3LLzRytHMQ==
  # 30 min
  secs_to_expire_access: 1800
  # 30 days
  secs_to_expire_refresh: 2592000

oauth2:
  redirect-uris: http://localhost:5500
